// ============================================
// AniGO — Puzzle Definitions (Stub / Sample Data)
// Will be replaced by full puzzle data
// ============================================

// Board cell constants
const E = 0; // Empty
const B = 1; // Black
const W = 2; // White

export const WORLDS = [
  {
    id: 'basics',
    name: 'Basics',
    nameKo: '기초',
    levels: ['p1-1', 'p1-2', 'p1-3', 'p1-4', 'p1-5', 'p1-6', 'p1-7', 'p1-8', 'p1-9', 'p1-10']
  },
  {
    id: 'capture',
    name: 'The Art of Capture',
    nameKo: '따먹기의 기술',
    levels: ['p2-1', 'p2-2', 'p2-3', 'p2-4', 'p2-5', 'p2-6', 'p2-7', 'p2-8', 'p2-9', 'p2-10']
  },
  {
    id: 'territory',
    name: 'Territory Master',
    nameKo: '영토의 달인',
    levels: ['p3-1', 'p3-2', 'p3-3', 'p3-4', 'p3-5', 'p3-6', 'p3-7', 'p3-8', 'p3-9', 'p3-10']
  },
  {
    id: 'spell_awakening',
    name: 'Spell Awakening',
    nameKo: '마법 각성',
    levels: ['p4-1', 'p4-2', 'p4-3', 'p4-4', 'p4-5', 'p4-6', 'p4-7', 'p4-8', 'p4-9', 'p4-10']
  },
  {
    id: 'void_walker',
    name: 'Void Walker',
    nameKo: '공허의 보행자',
    levels: ['p5-1', 'p5-2', 'p5-3', 'p5-4', 'p5-5', 'p5-6', 'p5-7', 'p5-8', 'p5-9', 'p5-10']
  },
  {
    id: 'trickster',
    name: "Trickster's Path",
    nameKo: '트릭스터의 길',
    levels: ['p6-1', 'p6-2', 'p6-3', 'p6-4', 'p6-5', 'p6-6', 'p6-7', 'p6-8', 'p6-9', 'p6-10']
  }
];

export const PUZZLES = [
  // ── World 1: Basics ──
  {
    id: 'p1-1',
    world: 'basics',
    name: 'First Capture',
    nameKo: '첫 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone',
    descriptionKo: '백돌 1개를 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Place a stone to take away the last liberty',
    hintKo: '마지막 활로를 막으세요',
    solution: [{ row: 4, col: 5 }]
  },
  {
    id: 'p1-2',
    world: 'basics',
    name: 'Edge Capture',
    nameKo: '변 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone on the edge',
    descriptionKo: '변에 있는 백돌을 잡으세요',
    board: [
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'White has only one liberty left',
    hintKo: '백돌의 활로가 하나 남았습니다',
    solution: [{ row: 0, col: 5 }]
  },
  {
    id: 'p1-3',
    world: 'basics',
    name: 'Corner Capture',
    nameKo: '귀 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone in the corner',
    descriptionKo: '귀에 있는 백돌을 잡으세요',
    board: [
      [W,B,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Corners only have 2 liberties',
    hintKo: '귀의 돌은 활로가 2개뿐입니다',
    solution: [{ row: 1, col: 0 }]
  },
  {
    id: 'p1-4',
    world: 'basics',
    name: 'Two Stone Capture',
    nameKo: '2개 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the 2 white stones',
    descriptionKo: '백돌 2개를 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Both white stones share the same liberty',
    hintKo: '두 백돌이 같은 활로를 공유합니다',
    solution: [{ row: 4, col: 5 }]
  },
  {
    id: 'p1-5',
    world: 'basics',
    name: 'First Taste of Magic',
    nameKo: '마법의 첫 맛',
    type: 'spell',
    difficulty: 1,
    description: 'Use Shatter to capture the white stone (it has 2 liberties — you can\'t capture normally!)',
    descriptionKo: '파쇄 마법으로 백돌을 잡으세요 (활로가 2개라 일반적으로는 잡을 수 없습니다!)',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['shatter'],
    spellUses: { shatter: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Select the Shatter spell, then target the white stone',
    hintKo: '파쇄 마법을 선택한 후 백돌을 클릭하세요',
    solution: [{ spell: 'shatter', row: 4, col: 4 }]
  },
  // p1-6: Three Stone Group
  {
    id: 'p1-6',
    world: 'basics',
    name: 'Three Stone Group',
    nameKo: '3개 돌 그룹',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the 3 white stones',
    descriptionKo: '백돌 3개를 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'The group has one shared liberty',
    hintKo: '그룹에 공유된 활로가 하나입니다',
    solution: [{ row: 4, col: 5 }]
  },
  // p1-7: Liberty Counting
  {
    id: 'p1-7',
    world: 'basics',
    name: 'Liberty Counting',
    nameKo: '활로 세기',
    type: 'capture',
    difficulty: 1,
    description: 'Fill the last liberty to capture',
    descriptionKo: '마지막 활로를 메워서 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'White has only one liberty remaining',
    hintKo: '백에 활로가 하나만 남았습니다',
    solution: [{ row: 5, col: 4 }]
  },
  // p1-8: Bottom Edge Capture
  {
    id: 'p1-8',
    world: 'basics',
    name: 'Bottom Edge',
    nameKo: '하변 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone on the bottom edge',
    descriptionKo: '하변의 백돌을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'The edge reduces liberties — find the last one',
    hintKo: '변은 활로를 줄입니다 — 마지막 하나를 찾으세요',
    solution: [{ row: 8, col: 5 }]
  },
  // p1-9: Surrounded Group
  {
    id: 'p1-9',
    world: 'basics',
    name: 'Surrounded',
    nameKo: '포위됨',
    type: 'capture',
    difficulty: 2,
    description: 'Capture the surrounded white pair',
    descriptionKo: '포위된 백돌 쌍을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,B,W,E,B,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Both white stones share the same last liberty',
    hintKo: '두 백돌이 마지막 활로를 공유합니다',
    solution: [{ row: 4, col: 4 }]
  },
  // p1-10: Big Group Capture
  {
    id: 'p1-10',
    world: 'basics',
    name: 'Big Group',
    nameKo: '큰 그룹',
    type: 'capture',
    difficulty: 2,
    description: 'Capture the 4-stone white group',
    descriptionKo: '백돌 4개 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 4 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'The entire group has only one liberty left',
    hintKo: '전체 그룹에 활로가 하나만 남았습니다',
    solution: [{ row: 5, col: 4 }]
  },

  // ── World 2: The Art of Capture ──
  // p2-1: Simple Atari
  {
    id: 'p2-1',
    world: 'capture',
    name: 'Simple Atari',
    nameKo: '단순 아타리',
    type: 'capture',
    difficulty: 1,
    description: 'Put the white group in atari and capture it',
    descriptionKo: '백 그룹을 아타리에 넣고 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'The two white stones share a single liberty',
    hintKo: '두 백돌이 하나의 활로를 공유합니다',
    solution: [{ row: 3, col: 4 }]
  },
  // p2-2: Double Atari
  {
    id: 'p2-2',
    world: 'capture',
    name: 'Double Atari',
    nameKo: '양 아타리',
    type: 'capture',
    difficulty: 2,
    description: 'Play a double atari to guarantee a capture',
    descriptionKo: '양 아타리로 반드시 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,B,W,E,W,B,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'One move puts two separate white stones in atari simultaneously',
    hintKo: '한 수로 두 백돌을 동시에 아타리에 넣으세요',
    solution: [{ row: 3, col: 4 }]
  },
  // p2-3: Edge Atari
  {
    id: 'p2-3',
    world: 'capture',
    name: 'Edge Atari',
    nameKo: '변 아타리',
    type: 'capture',
    difficulty: 2,
    description: 'Use the edge to capture the white group',
    descriptionKo: '변을 이용해 백 그룹을 잡으세요',
    board: [
      [E,E,B,W,W,B,E,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'The white pair on the edge has only one liberty left',
    hintKo: '변의 백돌 쌍에 활로가 하나뿐입니다',
    solution: [{ row: 1, col: 4 }]
  },
  // p2-4: Ladder Basics
  {
    id: 'p2-4',
    world: 'capture',
    name: 'Ladder Basics',
    nameKo: '축 기초',
    type: 'capture',
    difficulty: 2,
    description: 'Chase the white stone in a ladder to capture it',
    descriptionKo: '축으로 백돌을 몰아 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 9,
    optimalMoves: 1,
    hint: 'Keep reducing white to one liberty diagonally',
    hintKo: '백의 활로를 대각선으로 계속 줄이세요',
    solution: [{ row: 4, col: 4 }]
  },
  // p2-5: Loose Ladder (Net)
  {
    id: 'p2-5',
    world: 'capture',
    name: 'The Net',
    nameKo: '그물',
    type: 'capture',
    difficulty: 3,
    description: 'Use a net to trap the white stone',
    descriptionKo: '그물로 백돌을 가두세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,B,W,E,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 5,
    optimalMoves: 1,
    hint: 'Play diagonally to create an inescapable net',
    hintKo: '대각선으로 두어 탈출 불가능한 그물을 만드세요',
    solution: [{ row: 3, col: 4 }]
  },
  // p2-6: Snapback
  {
    id: 'p2-6',
    world: 'capture',
    name: 'Snapback',
    nameKo: '환격',
    type: 'capture',
    difficulty: 3,
    description: 'Sacrifice a stone to snapback and capture more',
    descriptionKo: '돌을 희생해 환격으로 더 많이 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,W,E,E,E,E],
      [E,E,B,W,E,B,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Play inside white\'s shape — they capture, then you recapture more',
    hintKo: '백 모양 안에 두세요 — 잡히면 바로 되잡으세요',
    solution: [{ row: 3, col: 5 }]
  },
  // p2-7: Connect and Capture
  {
    id: 'p2-7',
    world: 'capture',
    name: 'Connect and Capture',
    nameKo: '연결과 따먹기',
    type: 'capture',
    difficulty: 2,
    description: 'Connect your stones then capture the white group',
    descriptionKo: '돌을 연결한 후 백 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Connect your stones to close the last liberty',
    hintKo: '돌을 연결해 마지막 활로를 막으세요',
    solution: [{ row: 4, col: 4 }]
  },
  // p2-8: Capture Race
  {
    id: 'p2-8',
    world: 'capture',
    name: 'Capture Race',
    nameKo: '수상전',
    type: 'capture',
    difficulty: 3,
    description: 'Win the capture race — reduce white\'s liberties first',
    descriptionKo: '수상전에서 이기세요 — 백의 활로를 먼저 줄이세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,W,W,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,B,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Fill white\'s inside liberty to win the race',
    hintKo: '백의 안쪽 활로를 메워 수상전에서 이기세요',
    solution: [{ row: 4, col: 4 }]
  },
  // p2-9: Double Atari Fork
  {
    id: 'p2-9',
    world: 'capture',
    name: 'Fork Attack',
    nameKo: '양갈래 공격',
    type: 'capture',
    difficulty: 3,
    description: 'Play a double atari — white cannot save both groups',
    descriptionKo: '양 아타리를 두세요 — 백은 둘 다 살릴 수 없습니다',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,E,E,E,B,E,E],
      [E,E,B,W,E,W,B,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'One move threatens two separate groups at once',
    hintKo: '한 수로 두 그룹을 동시에 위협하세요',
    solution: [{ row: 3, col: 4 }]
  },
  // p2-10: Advanced Ladder
  {
    id: 'p2-10',
    world: 'capture',
    name: 'Ladder Breaker',
    nameKo: '축 깨기',
    type: 'capture',
    difficulty: 4,
    description: 'The ladder fails — use a net instead',
    descriptionKo: '축이 실패합니다 — 대신 그물을 사용하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,W,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 5,
    optimalMoves: 1,
    hint: 'A ladder breaker exists — use a loose net to capture instead',
    hintKo: '축이 막혀 있습니다 — 느슨한 그물로 잡으세요',
    solution: [{ row: 3, col: 5 }]
  },

  // ── World 3: Territory Master ──
  // p3-1: Corner Enclosure
  {
    id: 'p3-1',
    world: 'territory',
    name: 'Corner Enclosure',
    nameKo: '귀 굳히기',
    type: 'territory',
    difficulty: 2,
    description: 'Secure the corner territory with one move',
    descriptionKo: '한 수로 귀의 영토를 확보하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,B],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,B,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 6 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Close off the corner by connecting your stones',
    hintKo: '돌을 연결해 귀를 닫으세요',
    solution: [{ row: 7, col: 7 }]
  },
  // p3-2: Side Territory
  {
    id: 'p3-2',
    world: 'territory',
    name: 'Side Territory',
    nameKo: '변의 영토',
    type: 'territory',
    difficulty: 2,
    description: 'Claim territory along the side',
    descriptionKo: '변을 따라 영토를 차지하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 5 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Extend along the edge between your stones',
    hintKo: '돌 사이 변을 따라 확장하세요',
    solution: [{ row: 5, col: 0 }]
  },
  // p3-3: Block the Invasion
  {
    id: 'p3-3',
    world: 'territory',
    name: 'Block the Invasion',
    nameKo: '침입 차단',
    type: 'territory',
    difficulty: 2,
    description: 'Block white from invading your corner territory',
    descriptionKo: '백이 귀 영토에 침입하지 못하게 막으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,W,E,E],
      [E,E,E,E,E,E,E,B,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,B,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 4 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Block white\'s path into the corner',
    hintKo: '백의 귀 진입 경로를 막으세요',
    solution: [{ row: 7, col: 7 }]
  },
  // p3-4: Surround and Claim
  {
    id: 'p3-4',
    world: 'territory',
    name: 'Surround and Claim',
    nameKo: '둘러싸고 차지하기',
    type: 'territory',
    difficulty: 3,
    description: 'Complete the enclosure to claim territory',
    descriptionKo: '둘러싸기를 완성해 영토를 차지하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,B,B,E,E,E,E,E,E],
      [E,E,B,E,E,E,E,E,E],
      [E,E,B,E,E,E,E,E,E],
      [E,E,B,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 6 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Seal off the bottom-left corner',
    hintKo: '좌하귀를 봉쇄하세요',
    solution: [{ row: 5, col: 0 }]
  },
  // p3-5: Two-Point Extension
  {
    id: 'p3-5',
    world: 'territory',
    name: 'Two-Point Extension',
    nameKo: '2간 벌림',
    type: 'territory',
    difficulty: 2,
    description: 'Extend to build a territorial framework',
    descriptionKo: '벌려서 세력을 만드세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 4 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Extend two points along the edge',
    hintKo: '변을 따라 2칸 벌리세요',
    solution: [{ row: 8, col: 0 }]
  },
  // p3-6: Defend the Border
  {
    id: 'p3-6',
    world: 'territory',
    name: 'Defend the Border',
    nameKo: '경계 방어',
    type: 'territory',
    difficulty: 3,
    description: 'Reinforce your border before white breaks through',
    descriptionKo: '백이 뚫기 전에 경계를 강화하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,B,B,E,B,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,W,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 8 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Close the gap in your wall',
    hintKo: '벽의 틈을 메우세요',
    solution: [{ row: 3, col: 3 }]
  },
  // p3-7: Corner Approach Defense
  {
    id: 'p3-7',
    world: 'territory',
    name: 'Corner Defense',
    nameKo: '귀 방어',
    type: 'territory',
    difficulty: 3,
    description: 'Defend your corner from white\'s approach',
    descriptionKo: '백의 접근에서 귀를 방어하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,W,E,B,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,B,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 3 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Play between white and your corner to keep territory',
    hintKo: '백과 귀 사이에 두어 영토를 지키세요',
    solution: [{ row: 6, col: 6 }]
  },
  // p3-8: Cut and Conquer
  {
    id: 'p3-8',
    world: 'territory',
    name: 'Cut and Conquer',
    nameKo: '끊기와 정복',
    type: 'territory',
    difficulty: 3,
    description: 'Cut white\'s invasion stones to keep your territory',
    descriptionKo: '백의 침입 돌을 끊어 영토를 지키세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,B,B,E,B,B,B,B,B],
      [E,E,W,W,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 10 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Close the gap to seal your territory and strand white',
    hintKo: '틈을 막아 영토를 봉쇄하고 백을 고립시키세요',
    solution: [{ row: 4, col: 3 }]
  },
  // p3-9: Big Corner
  {
    id: 'p3-9',
    world: 'territory',
    name: 'Big Corner',
    nameKo: '큰 귀',
    type: 'territory',
    difficulty: 3,
    description: 'Claim a large corner territory',
    descriptionKo: '큰 귀 영토를 차지하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,B,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,B,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 8 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Connect your stones to the corner and edge',
    hintKo: '돌을 귀와 변에 연결하세요',
    solution: [{ row: 2, col: 8 }]
  },
  // p3-10: Invasion Punishment
  {
    id: 'p3-10',
    world: 'territory',
    name: 'Invasion Punishment',
    nameKo: '침입 응징',
    type: 'territory',
    difficulty: 4,
    description: 'White invaded your territory — punish and capture',
    descriptionKo: '백이 영토에 침입했습니다 — 응징하고 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,B,B,B,B],
      [E,E,E,E,E,B,W,E,B],
      [E,E,E,E,E,B,E,W,B],
      [E,E,E,E,E,B,B,E,B],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: {},
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Seal the inside to capture the invaders',
    hintKo: '안쪽을 봉쇄해 침입자를 잡으세요',
    solution: [{ row: 8, col: 7 }]
  },

  // ── World 4: Spell Awakening ──
  // p4-1: Shatter Introduction
  {
    id: 'p4-1',
    world: 'spell_awakening',
    name: 'Shatter Strike',
    nameKo: '파쇄의 일격',
    type: 'spell',
    difficulty: 2,
    description: 'Use Shatter to destroy a white stone in atari',
    descriptionKo: '파쇄로 아타리 상태의 백돌을 파괴하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['shatter'],
    spellUses: { shatter: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'White has only one liberty — Shatter destroys stones in atari',
    hintKo: '백에 활로가 하나뿐 — 파쇄는 아타리 돌을 파괴합니다',
    solution: [{ spell: 'shatter', row: 4, col: 4 }]
  },
  // p4-2: Shatter Chain
  {
    id: 'p4-2',
    world: 'spell_awakening',
    name: 'Shatter Chain',
    nameKo: '파쇄 연쇄',
    type: 'spell',
    difficulty: 2,
    description: 'Shatter the key stone to capture the whole group',
    descriptionKo: '핵심 돌에 파쇄를 써서 전체 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['shatter'],
    spellUses: { shatter: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Shatter the enclosed white group directly',
    hintKo: '둘러싸인 백 그룹에 직접 파쇄를 사용하세요',
    solution: [{ spell: 'shatter', row: 3, col: 4 }]
  },
  // p4-3: Stone Skin Defense
  {
    id: 'p4-3',
    world: 'spell_awakening',
    name: 'Stone Skin Shield',
    nameKo: '석갑 방어',
    type: 'spell',
    difficulty: 2,
    description: 'Use Stone Skin to protect your key stone from capture',
    descriptionKo: '석갑으로 핵심 돌을 잡힘에서 보호하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,W,E,E,E,E],
      [E,E,E,W,B,W,E,E,E],
      [E,E,E,E,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'survival', count: 1 },
    availableSpells: ['stoneskin'],
    spellUses: { stoneskin: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Your stone is surrounded — make it invincible with Stone Skin',
    hintKo: '돌이 둘러싸여 있습니다 — 석갑으로 무적으로 만드세요',
    solution: [{ spell: 'stoneskin', row: 3, col: 4 }]
  },
  // p4-4: Mirage Decoy
  {
    id: 'p4-4',
    world: 'spell_awakening',
    name: 'Mirage Decoy',
    nameKo: '신기루 미끼',
    type: 'spell',
    difficulty: 3,
    description: 'Place a Mirage to lure white into a bad move',
    descriptionKo: '신기루를 놓아 백을 유인하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,B,W,E,B,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['mirage'],
    spellUses: { mirage: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Place a phantom stone to confuse white, then capture',
    hintKo: '환상 돌로 백을 혼란시킨 후 잡으세요',
    solution: [{ spell: 'mirage', row: 4, col: 3 }, { row: 4, col: 4 }]
  },
  // p4-5: Shatter + Capture Combo
  {
    id: 'p4-5',
    world: 'spell_awakening',
    name: 'Shatter and Seize',
    nameKo: '파쇄 후 장악',
    type: 'spell',
    difficulty: 3,
    description: 'Shatter the key defender, then capture the group',
    descriptionKo: '핵심 수비수를 파쇄한 후 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,E,B,B,E,B,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: ['shatter'],
    spellUses: { shatter: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Shatter the white stone with two liberties, then close the last one',
    hintKo: '활로 2개인 백돌에 파쇄 후 마지막 활로를 막으세요',
    solution: [{ spell: 'shatter', row: 3, col: 5 }, { row: 4, col: 5 }]
  },
  // p4-6: Stone Skin Anchor
  {
    id: 'p4-6',
    world: 'spell_awakening',
    name: 'Anchor Point',
    nameKo: '기반석',
    type: 'spell',
    difficulty: 3,
    description: 'Fortify your cutting stone to split white\'s groups',
    descriptionKo: '끊기 돌을 강화해 백 그룹을 분리하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,W,W,E,E,E,E],
      [E,E,W,B,E,W,E,E,E],
      [E,E,E,W,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'survival', count: 1 },
    availableSpells: ['stoneskin'],
    spellUses: { stoneskin: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Your cutting stone is in danger — make it indestructible',
    hintKo: '끊기 돌이 위험합니다 — 무적으로 만드세요',
    solution: [{ spell: 'stoneskin', row: 3, col: 3 }]
  },
  // p4-7: Mirage Invasion
  {
    id: 'p4-7',
    world: 'spell_awakening',
    name: 'Phantom Invasion',
    nameKo: '환영의 침입',
    type: 'spell',
    difficulty: 3,
    description: 'Use Mirage to create a phantom stone inside white\'s territory',
    descriptionKo: '신기루로 백의 영토 안에 환영 돌을 만드세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [W,W,W,W,E,E,E,E,E],
      [E,E,E,W,E,E,E,E,E],
      [E,E,E,W,E,E,E,E,E],
      [E,E,E,W,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 3 },
    availableSpells: ['mirage'],
    spellUses: { mirage: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Place a phantom to threaten white\'s enclosed area',
    hintKo: '환영으로 백의 둘러싸인 영역을 위협하세요',
    solution: [{ spell: 'mirage', row: 7, col: 1 }]
  },
  // p4-8: Shatter Escape
  {
    id: 'p4-8',
    world: 'spell_awakening',
    name: 'Shatter Escape',
    nameKo: '파쇄 탈출',
    type: 'spell',
    difficulty: 3,
    description: 'Your group is trapped — Shatter a wall stone to escape',
    descriptionKo: '그룹이 갇혔습니다 — 벽 돌을 파쇄해 탈출하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,W,W,W,E,E,E],
      [E,E,W,B,B,W,E,E,E],
      [E,E,E,W,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'survival', count: 2 },
    availableSpells: ['shatter'],
    spellUses: { shatter: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Shatter a white stone on the wall to open an escape route',
    hintKo: '벽의 백돌을 파쇄해 탈출구를 열으세요',
    solution: [{ spell: 'shatter', row: 4, col: 3 }]
  },
  // p4-9: Combined Arms
  {
    id: 'p4-9',
    world: 'spell_awakening',
    name: 'Combined Arms',
    nameKo: '합동 작전',
    type: 'spell',
    difficulty: 4,
    description: 'Use Stone Skin then play to capture the enemy group',
    descriptionKo: '석갑 후 수를 두어 적 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,B,W,B,W,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 4 },
    availableSpells: ['stoneskin'],
    spellUses: { stoneskin: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Protect your cutting stone with Stone Skin, then fill the liberty',
    hintKo: '끊기 돌을 석갑으로 보호한 후 활로를 메우세요',
    solution: [{ spell: 'stoneskin', row: 4, col: 4 }, { row: 4, col: 5 }]
  },
  // p4-10: Triple Spell
  {
    id: 'p4-10',
    world: 'spell_awakening',
    name: 'Triple Awakening',
    nameKo: '삼중 각성',
    type: 'spell',
    difficulty: 4,
    description: 'Use all three spells wisely to capture the fortified group',
    descriptionKo: '세 가지 마법을 현명하게 사용해 강화된 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,B,W,E,W,B,E,E],
      [E,E,E,B,B,E,B,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 5 },
    availableSpells: ['shatter', 'stoneskin', 'mirage'],
    spellUses: { shatter: 1, stoneskin: 1, mirage: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Shatter the group then seal the remaining liberty',
    hintKo: '그룹에 파쇄 후 남은 활로를 봉쇄하세요',
    solution: [{ spell: 'shatter', row: 3, col: 5 }, { row: 5, col: 5 }]
  },

  // ── World 5: Void Walker ──
  // p5-1: Void Rift Introduction
  {
    id: 'p5-1',
    world: 'void_walker',
    name: 'Rift Opening',
    nameKo: '균열 열기',
    type: 'spell',
    difficulty: 3,
    description: 'Use Void Rift to remove a key intersection and capture',
    descriptionKo: '공허의 균열로 핵심 교차점을 제거하고 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['voidrift'],
    spellUses: { voidrift: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Remove white\'s escape liberty with Void Rift',
    hintKo: '공허의 균열로 백의 탈출 활로를 제거하세요',
    solution: [{ spell: 'voidrift', row: 3, col: 4 }]
  },
  // p5-2: Earthen Wall Barrier
  {
    id: 'p5-2',
    world: 'void_walker',
    name: 'Wall of Earth',
    nameKo: '대지의 벽',
    type: 'spell',
    difficulty: 3,
    description: 'Use Earthen Wall to block white\'s escape route',
    descriptionKo: '대지의 벽으로 백의 탈출로를 막으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['earthenwall'],
    spellUses: { earthenwall: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Place a wall to block white\'s liberties, then capture',
    hintKo: '벽으로 백의 활로를 막은 후 잡으세요',
    solution: [{ spell: 'earthenwall', row: 4, col: 4, dir: 'h' }, { row: 5, col: 3 }]
  },
  // p5-3: Warp Gate Teleport
  {
    id: 'p5-3',
    world: 'void_walker',
    name: 'Warp Strike',
    nameKo: '워프 공격',
    type: 'spell',
    difficulty: 3,
    description: 'Use Warp Gate to teleport a stone into the enemy\'s weakness',
    descriptionKo: '워프 게이트로 돌을 적의 약점에 전송하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,B,E,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,B,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['warpgate'],
    spellUses: { warpgate: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Teleport the isolated black stone to fill white\'s last liberty',
    hintKo: '고립된 흑돌을 백의 마지막 활로로 전송하세요',
    solution: [{ spell: 'warpgate', row: 7, col: 1, toRow: 5, toCol: 4 }]
  },
  // p5-4: Void Rift Cascade
  {
    id: 'p5-4',
    world: 'void_walker',
    name: 'Rift Cascade',
    nameKo: '균열 연쇄',
    type: 'spell',
    difficulty: 4,
    description: 'Void Rift can cascade — remove a stone to trigger a chain',
    descriptionKo: '공허의 균열이 연쇄됩니다 — 돌을 제거해 연쇄를 일으키세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,B,W,E,W,B,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 5 },
    availableSpells: ['voidrift'],
    spellUses: { voidrift: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Void Rift destroys a white stone — the group loses its last liberty',
    hintKo: '공허의 균열이 백돌을 파괴하면 그룹이 활로를 잃습니다',
    solution: [{ spell: 'voidrift', row: 4, col: 4 }]
  },
  // p5-5: Earthen Wall Territory
  {
    id: 'p5-5',
    world: 'void_walker',
    name: 'Fortress Wall',
    nameKo: '요새의 벽',
    type: 'spell',
    difficulty: 3,
    description: 'Build an Earthen Wall to secure your territory',
    descriptionKo: '대지의 벽으로 영토를 확보하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 6 },
    availableSpells: ['earthenwall'],
    spellUses: { earthenwall: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Place a wall between your stones to create a sealed territory',
    hintKo: '돌 사이에 벽을 세워 영토를 봉쇄하세요',
    solution: [{ spell: 'earthenwall', row: 6, col: 1, dir: 'v' }]
  },
  // p5-6: Warp Gate Rescue
  {
    id: 'p5-6',
    world: 'void_walker',
    name: 'Warp Rescue',
    nameKo: '워프 구출',
    type: 'spell',
    difficulty: 3,
    description: 'Teleport your endangered stone to safety',
    descriptionKo: '위험한 돌을 안전한 곳으로 전송하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,W,W,E,E,E,E],
      [E,E,W,B,W,E,E,E,E],
      [E,E,E,W,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'survival', count: 1 },
    availableSpells: ['warpgate'],
    spellUses: { warpgate: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Your stone is almost captured — warp it to an open area',
    hintKo: '돌이 거의 잡힙니다 — 열린 곳으로 워프하세요',
    solution: [{ spell: 'warpgate', row: 3, col: 3, toRow: 6, toCol: 4 }]
  },
  // p5-7: Void + Capture
  {
    id: 'p5-7',
    world: 'void_walker',
    name: 'Void Trap',
    nameKo: '공허의 함정',
    type: 'spell',
    difficulty: 4,
    description: 'Remove a liberty with Void Rift, then play to capture',
    descriptionKo: '공허의 균열로 활로를 제거한 후 두어서 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: ['voidrift'],
    spellUses: { voidrift: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Void Rift one liberty, then fill the other to capture all three',
    hintKo: '균열로 활로 하나를 제거한 후 나머지를 메워 셋 다 잡으세요',
    solution: [{ spell: 'voidrift', row: 2, col: 4 }, { row: 4, col: 4 }]
  },
  // p5-8: Earthen Wall Seal
  {
    id: 'p5-8',
    world: 'void_walker',
    name: 'Sealed Fate',
    nameKo: '봉인된 운명',
    type: 'spell',
    difficulty: 4,
    description: 'Use Earthen Wall to seal a group with no escape',
    descriptionKo: '대지의 벽으로 그룹을 탈출 불가하게 봉인하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,E,E,E,E,E],
      [E,E,B,W,W,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['earthenwall'],
    spellUses: { earthenwall: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Wall off white\'s escape, then close the final liberty',
    hintKo: '벽으로 백의 탈출을 막고 마지막 활로를 닫으세요',
    solution: [{ spell: 'earthenwall', row: 2, col: 4, dir: 'v' }, { row: 4, col: 4 }]
  },
  // p5-9: Warp + Capture
  {
    id: 'p5-9',
    world: 'void_walker',
    name: 'Dimensional Strike',
    nameKo: '차원의 일격',
    type: 'spell',
    difficulty: 4,
    description: 'Warp your stone into position to capture a group',
    descriptionKo: '돌을 워프해 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,B,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['warpgate'],
    spellUses: { warpgate: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Warp the distant stone directly into the last liberty',
    hintKo: '먼 돌을 마지막 활로로 직접 워프하세요',
    solution: [{ spell: 'warpgate', row: 7, col: 6, toRow: 4, toCol: 4 }]
  },
  // p5-10: Void Mastery
  {
    id: 'p5-10',
    world: 'void_walker',
    name: 'Void Mastery',
    nameKo: '공허 마스터',
    type: 'spell',
    difficulty: 5,
    description: 'Combine Void Rift, Earthen Wall, and Warp Gate for total control',
    descriptionKo: '공허의 균열, 대지의 벽, 워프 게이트를 합쳐 완전히 지배하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,E,E,B,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,B,W,E,E,B,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,B,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 4 },
    availableSpells: ['voidrift', 'earthenwall', 'warpgate'],
    spellUses: { voidrift: 1, earthenwall: 1, warpgate: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Void Rift the escape point, then warp a stone in to seal the group',
    hintKo: '탈출 지점에 균열을 쓴 후 돌을 워프해 그룹을 봉인하세요',
    solution: [{ spell: 'voidrift', row: 2, col: 4 }, { spell: 'warpgate', row: 7, col: 1, toRow: 5, toCol: 4 }]
  },

  // ── World 6: Trickster's Path ──
  // p6-1: Snare Introduction
  {
    id: 'p6-1',
    world: 'trickster',
    name: 'Hidden Snare',
    nameKo: '숨겨진 올무',
    type: 'spell',
    difficulty: 3,
    description: 'Place a Snare to trap the opponent\'s next move',
    descriptionKo: '올무를 놓아 상대의 다음 수를 가두세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['snare'],
    spellUses: { snare: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Place a snare where white wants to escape, then capture',
    hintKo: '백이 탈출하려는 곳에 올무를 놓은 후 잡으세요',
    solution: [{ spell: 'snare', row: 4, col: 4 }, { row: 4, col: 5 }]
  },
  // p6-2: Nine Lives Survival
  {
    id: 'p6-2',
    world: 'trickster',
    name: 'Nine Lives',
    nameKo: '아홉 개의 목숨',
    type: 'spell',
    difficulty: 3,
    description: 'Use Nine Lives to resurrect your captured stone',
    descriptionKo: '아홉 개의 목숨으로 잡힌 돌을 부활시키세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,W,E,E,E,E],
      [E,E,E,W,B,W,E,E,E],
      [E,E,E,E,W,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'survival', count: 1 },
    availableSpells: ['ninelives'],
    spellUses: { ninelives: 1 },
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Your stone will die — Nine Lives brings it back',
    hintKo: '돌이 죽을 것입니다 — 아홉 목숨이 부활시킵니다',
    solution: [{ spell: 'ninelives', row: 3, col: 4 }]
  },
  // p6-3: Snare + Capture
  {
    id: 'p6-3',
    world: 'trickster',
    name: 'Trap and Snap',
    nameKo: '함정과 덫',
    type: 'spell',
    difficulty: 3,
    description: 'Snare the escape route, then play to capture',
    descriptionKo: '탈출로에 올무를 놓은 후 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,B,W,W,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['snare'],
    spellUses: { snare: 1 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Snare the liberty, then play atari to capture',
    hintKo: '활로에 올무를 놓은 후 아타리로 잡으세요',
    solution: [{ spell: 'snare', row: 3, col: 4 }, { row: 4, col: 4 }]
  },
  // p6-4: Nine Lives Counter
  {
    id: 'p6-4',
    world: 'trickster',
    name: 'Undying Counter',
    nameKo: '불사의 반격',
    type: 'spell',
    difficulty: 4,
    description: 'Let your stone die, revive with Nine Lives, and counter-attack',
    descriptionKo: '돌을 죽게 한 후 부활시키고 반격하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,B,E,E,E],
      [E,E,B,W,B,W,B,E,E],
      [E,E,E,W,E,W,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['ninelives'],
    spellUses: { ninelives: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Protect your cutting stone with Nine Lives, then fill liberties',
    hintKo: '끊기 돌에 아홉 목숨을 쓴 후 활로를 메우세요',
    solution: [{ spell: 'ninelives', row: 3, col: 4 }, { row: 4, col: 4 }]
  },
  // p6-5: Snare Territory
  {
    id: 'p6-5',
    world: 'trickster',
    name: 'Minefield',
    nameKo: '지뢰밭',
    type: 'spell',
    difficulty: 3,
    description: 'Place snares to protect your territory from invasion',
    descriptionKo: '올무를 놓아 영토를 침입에서 보호하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [B,B,B,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'territory', count: 8 },
    availableSpells: ['snare'],
    spellUses: { snare: 2 },
    maxMoves: 4,
    optimalMoves: 2,
    hint: 'Snare the gaps in your wall to make invasion impossible',
    hintKo: '벽의 틈에 올무를 놓아 침입을 불가능하게 하세요',
    solution: [{ spell: 'snare', row: 5, col: 3 }, { row: 5, col: 3 }]
  },
  // p6-6: Combo — Snare + Shatter
  {
    id: 'p6-6',
    world: 'trickster',
    name: 'Shatter Trap',
    nameKo: '파쇄 함정',
    type: 'combo',
    difficulty: 4,
    description: 'Snare the escape, then Shatter the weakened group',
    descriptionKo: '탈출에 올무를 놓은 후 약해진 그룹에 파쇄를 쓰세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,B,W,W,E,E,E,E],
      [E,E,B,W,E,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: ['snare', 'shatter'],
    spellUses: { snare: 1, shatter: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Snare white\'s escape, then Shatter the group',
    hintKo: '백 탈출에 올무를 놓은 후 그룹에 파쇄를 쓰세요',
    solution: [{ spell: 'snare', row: 3, col: 4 }, { spell: 'shatter', row: 3, col: 3 }]
  },
  // p6-7: Combo — Nine Lives + Sacrifice
  {
    id: 'p6-7',
    world: 'trickster',
    name: 'Sacrifice and Return',
    nameKo: '희생과 귀환',
    type: 'combo',
    difficulty: 4,
    description: 'Sacrifice your stone inside, revive it, and capture from within',
    descriptionKo: '안에 돌을 희생하고 부활시켜 내부에서 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,B,E,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,B,W,E,B,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 3 },
    availableSpells: ['ninelives'],
    spellUses: { ninelives: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Play inside, use Nine Lives on that stone, let it be captured and revive',
    hintKo: '안에 두고 그 돌에 아홉 목숨을 쓰세요, 잡히면 부활합니다',
    solution: [{ row: 4, col: 4 }, { spell: 'ninelives', row: 4, col: 4 }]
  },
  // p6-8: Combo — Mirage + Snare
  {
    id: 'p6-8',
    world: 'trickster',
    name: 'Phantom Trap',
    nameKo: '환영의 덫',
    type: 'combo',
    difficulty: 4,
    description: 'Use Mirage to bait, Snare to punish, then capture',
    descriptionKo: '신기루로 유인하고 올무로 응징한 후 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,B,W,E,E,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: ['mirage', 'snare'],
    spellUses: { mirage: 1, snare: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Place a snare on white\'s escape, then play to capture',
    hintKo: '백 탈출에 올무를 놓고 잡으세요',
    solution: [{ spell: 'snare', row: 4, col: 3 }, { row: 4, col: 4 }]
  },
  // p6-9: Full Combo
  {
    id: 'p6-9',
    world: 'trickster',
    name: 'Grand Trickster',
    nameKo: '대 트릭스터',
    type: 'combo',
    difficulty: 5,
    description: 'Use Snare, Shatter, and Stone Skin to dominate the board',
    descriptionKo: '올무, 파쇄, 석갑을 사용해 판을 지배하세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,E,B,B,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,B,W,B,W,B,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 5 },
    availableSpells: ['snare', 'shatter', 'stoneskin'],
    spellUses: { snare: 1, shatter: 1, stoneskin: 1 },
    maxMoves: 5,
    optimalMoves: 2,
    hint: 'Protect your cutting stone, then shatter the weakened group',
    hintKo: '끊기 돌을 보호한 후 약해진 그룹에 파쇄를 쓰세요',
    solution: [{ spell: 'stoneskin', row: 4, col: 4 }, { spell: 'shatter', row: 3, col: 3 }]
  },
  // p6-10: Ultimate Combo
  {
    id: 'p6-10',
    world: 'trickster',
    name: 'Trickster Finale',
    nameKo: '트릭스터 피날레',
    type: 'combo',
    difficulty: 5,
    description: 'Master all your tricks — combine spells to solve the impossible puzzle',
    descriptionKo: '모든 트릭을 마스터하세요 — 마법을 조합해 불가능한 퍼즐을 풀으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,B,B,B,B,B,E,E],
      [E,E,B,W,W,W,B,E,E],
      [E,E,B,W,E,W,B,E,E],
      [E,E,B,W,W,E,B,E,E],
      [E,E,E,B,E,B,E,E,E],
      [E,B,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 6 },
    availableSpells: ['voidrift', 'shatter', 'warpgate', 'snare'],
    spellUses: { voidrift: 1, shatter: 1, warpgate: 1, snare: 1 },
    maxMoves: 6,
    optimalMoves: 3,
    hint: 'Void Rift the inner escape, warp a stone in, then shatter to finish',
    hintKo: '내부 탈출에 균열, 돌을 워프, 파쇄로 마무리하세요',
    solution: [{ spell: 'voidrift', row: 4, col: 4 }, { spell: 'warpgate', row: 7, col: 1, toRow: 6, toCol: 4 }, { spell: 'shatter', row: 5, col: 3 }]
  }
];
