// ============================================
// AniGO — Puzzle Definitions (Stub / Sample Data)
// Will be replaced by full puzzle data
// ============================================

// Board cell constants
const E = 0; // Empty
const B = 1; // Black
const W = 2; // White

export const WORLDS = [
  {
    id: 'basics',
    name: 'Basics',
    nameKo: '기초',
    levels: ['p1-1', 'p1-2', 'p1-3', 'p1-4', 'p1-5', 'p1-6', 'p1-7', 'p1-8', 'p1-9', 'p1-10']
  },
  {
    id: 'capture',
    name: 'Capture Training',
    nameKo: '따먹기 훈련',
    levels: ['p2-1', 'p2-2', 'p2-3', 'p2-4', 'p2-5', 'p2-6', 'p2-7', 'p2-8', 'p2-9', 'p2-10']
  },
  {
    id: 'spells',
    name: 'Spell Mastery',
    nameKo: '마법 마스터',
    levels: ['p3-1', 'p3-2', 'p3-3', 'p3-4', 'p3-5', 'p3-6', 'p3-7', 'p3-8', 'p3-9', 'p3-10']
  }
];

export const PUZZLES = [
  // ── World 1: Basics ──
  {
    id: 'p1-1',
    world: 'basics',
    name: 'First Capture',
    nameKo: '첫 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone',
    descriptionKo: '백돌 1개를 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Place a stone to take away the last liberty',
    hintKo: '마지막 활로를 막으세요',
    solution: [{ row: 4, col: 5 }]
  },
  {
    id: 'p1-2',
    world: 'basics',
    name: 'Edge Capture',
    nameKo: '변 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone on the edge',
    descriptionKo: '변에 있는 백돌을 잡으세요',
    board: [
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'White has only one liberty left',
    hintKo: '백돌의 활로가 하나 남았습니다',
    solution: [{ row: 0, col: 5 }]
  },
  {
    id: 'p1-3',
    world: 'basics',
    name: 'Corner Capture',
    nameKo: '귀 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the white stone in the corner',
    descriptionKo: '귀에 있는 백돌을 잡으세요',
    board: [
      [W,B,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Corners only have 2 liberties',
    hintKo: '귀의 돌은 활로가 2개뿐입니다',
    solution: [{ row: 1, col: 0 }]
  },
  {
    id: 'p1-4',
    world: 'basics',
    name: 'Two Stone Capture',
    nameKo: '2개 따먹기',
    type: 'capture',
    difficulty: 1,
    description: 'Capture the 2 white stones',
    descriptionKo: '백돌 2개를 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Both white stones share the same liberty',
    hintKo: '두 백돌이 같은 활로를 공유합니다',
    solution: [{ row: 4, col: 5 }]
  },
  {
    id: 'p1-5',
    world: 'basics',
    name: 'Ladder Start',
    nameKo: '축머리',
    type: 'capture',
    difficulty: 2,
    description: 'Start a ladder to capture',
    descriptionKo: '축을 시작해 백돌을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 5,
    optimalMoves: 1,
    hint: 'Reduce white to one liberty',
    hintKo: '백의 활로를 하나로 줄이세요',
    solution: [{ row: 3, col: 4 }]
  },
  // Placeholder levels for world 1
  ...['p1-6','p1-7','p1-8','p1-9','p1-10'].map((id, i) => ({
    id,
    world: 'basics',
    name: `Basic ${i + 6}`,
    nameKo: `기초 ${i + 6}`,
    type: 'capture',
    difficulty: 1,
    description: 'Capture the marked stones',
    descriptionKo: '표시된 돌을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 1 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Find the last liberty',
    hintKo: '마지막 활로를 찾으세요',
    solution: [{ row: 3, col: 5 }]
  })),

  // ── World 2: Capture Training (placeholders) ──
  ...Array.from({length: 10}, (_, i) => ({
    id: `p2-${i+1}`,
    world: 'capture',
    name: `Capture ${i + 1}`,
    nameKo: `따먹기 ${i + 1}`,
    type: 'capture',
    difficulty: 2,
    description: 'Capture the white group',
    descriptionKo: '백 그룹을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,B,B,E,E,E,E],
      [E,E,B,W,W,B,E,E,E],
      [E,E,E,B,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: [],
    spellUses: [],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Close the last liberty of the group',
    hintKo: '그룹의 마지막 활로를 닫으세요',
    solution: [{ row: 4, col: 4 }]
  })),

  // ── World 3: Spell Mastery (placeholders) ──
  ...Array.from({length: 10}, (_, i) => ({
    id: `p3-${i+1}`,
    world: 'spells',
    name: `Spell ${i + 1}`,
    nameKo: `마법 ${i + 1}`,
    type: 'spell_capture',
    difficulty: 3,
    description: 'Use your spell, then capture',
    descriptionKo: '마법을 쓴 후 돌을 잡으세요',
    board: [
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,B,W,B,E,E,E],
      [E,E,E,E,B,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
      [E,E,E,E,E,E,E,E,E],
    ],
    playerColor: 1,
    goal: { type: 'capture', count: 2 },
    availableSpells: ['shatter'],
    spellUses: [1],
    maxMoves: 3,
    optimalMoves: 1,
    hint: 'Use Shatter on the white group',
    hintKo: '파쇄를 백 그룹에 사용하세요',
    solution: [{ spell: 'shatter', row: 3, col: 4 }]
  }))
];
